# Generated by Django 3.2.13 on 2022-07-09 08:12

from django.db import migrations

import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0013_auto_20220709_0809"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="discounts",
            field=djstripe.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="upcominginvoice",
            name="discounts",
            field=djstripe.fields.JSONField(blank=True, null=True),
        ),
    ]
