# Generated by Django 3.2.13 on 2022-07-09 08:43

from django.db import migrations

import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ("djstripe", "0014_auto_20220709_0812"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceitem",
            name="discounts",
            field=djstripe.fields.JSONField(blank=True, null=True),
        ),
    ]
