name: Build and deploy docs

on:
  push:
    branches: [master]
  
  workflow_dispatch: # to trigger manually
  
jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
          python-version: 3.9

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.1.11

    - name: Install dependencies
      run: poetry install -E docs

    - name: Deploy docs to Github Pages
      run: poetry run mkdocs gh-deploy --force